"use client";
import { useState } from "react";
import { KeyRound, Pencil, Plus, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import type { CloudPanelUser } from "@/types/cloudpanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function UserManager({ initialUsers, sites }: { initialUsers: CloudPanelUser[]; sites: string[] }) {
  const [users, setUsers] = useState(initialUsers); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<CloudPanelUser | null>(null); const [busy, setBusy] = useState(false);
  async function act(body: Record<string, unknown>) { setBusy(true); try { const result = await fetch("/api/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }).then((r) => r.json()); if (!result.success) throw new Error(result.error.message); const next = await fetch("/api/users").then((r) => r.json()); setUsers(next.data.users); toast.success("User updated"); return true; } catch (error) { toast.error(error instanceof Error ? error.message : "Operation failed"); return false; } finally { setBusy(false); } }
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex justify-between"><div><h2 className="text-2xl font-bold">Users</h2><p className="mt-1 text-sm text-slate-500">CloudPanel administrators, site managers, and site users.</p></div><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Add user</Button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{users.map((user) => <section key={user.id} className="rounded-2xl border bg-white p-5 shadow-card"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-panel-50 text-panel-600"><UserRound /></span><span className={`h-fit rounded-full px-2 py-1 text-xs ${user.status === false ? "bg-red-50 text-red-600" : "bg-emerald-50 text-emerald-600"}`}>{user.status === false ? "Disabled" : "Active"}</span></div><h3 className="mt-4 font-bold">{user.displayName || user.username}</h3><p className="text-sm text-slate-500">{user.username} · {user.role}</p><p className="mt-2 text-xs text-slate-400">{user.email}</p><p className="mt-3 text-xs text-slate-500">{user.sites?.length ? `${user.sites.length} assigned sites` : user.role === "admin" ? "All sites" : "No sites"}</p><div className="mt-4 flex gap-1"><Button variant="outline" size="sm" onClick={() => setEditing(user)}><Pencil className="h-4 w-4" /> Edit</Button><Button variant="outline" size="sm" onClick={() => { const password = prompt(`New password for ${user.username}`); if (password) void act({ action: "reset-password", username: user.username, password }); }}><KeyRound className="h-4 w-4" /> Password</Button><Button variant="ghost" size="icon" onClick={() => { if (confirm(`Delete ${user.username}?`)) void act({ action: "delete", username: user.username }); }}><Trash2 className="h-4 w-4 text-red-500" /></Button></div></section>)}</div>
    {open && <UserModal title="Add CloudPanel user" close={() => setOpen(false)}><form className="space-y-4" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); body.sites = form.getAll("sites").join(","); if (await act({ action: "add", ...body })) setOpen(false); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" name="firstName" /><Field label="Last name" name="lastName" /><Field label="Username" name="username" /><Field label="Email" name="email" type="email" /><Field label="Password" name="password" type="password" /><RoleSelect /></div><SiteSelect sites={sites} /><Button disabled={busy}>Create user</Button></form></UserModal>}
    {editing && <UserModal title={`Edit ${editing.username}`} close={() => setEditing(null)}><form className="space-y-5" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await act({ action: "update", username: editing.username, role: form.get("role"), status: form.get("status") === "true", sites: form.getAll("sites") })) setEditing(null); }}><RoleSelect value={editing.role} /><label className="flex items-center gap-3 rounded-xl border p-4 text-sm font-medium"><input type="checkbox" name="status" value="true" defaultChecked={editing.status !== false} />Account enabled</label><SiteSelect sites={sites} selected={editing.sites} /><Button disabled={busy}>Save user</Button></form></UserModal>}
  </div>;
}
function Field({ label, name, type = "text" }: { label: string; name: string; type?: string }) { return <div><Label>{label}</Label><Input name={name} type={type} minLength={type === "password" ? 12 : undefined} required /></div>; }
function RoleSelect({ value = "user" }: { value?: string }) { return <div><Label>Role</Label><select name="role" defaultValue={value} className="h-11 w-full rounded-lg border px-3"><option value="user">User</option><option value="site-manager">Site manager</option><option value="admin">Admin</option></select></div>; }
function SiteSelect({ sites, selected = [] }: { sites: string[]; selected?: string[] }) { return <div><Label>Assigned sites (User role)</Label><select name="sites" multiple defaultValue={selected} className="mt-1 min-h-32 w-full rounded-lg border p-2">{sites.map((site) => <option key={site}>{site}</option>)}</select><p className="mt-1 text-xs text-slate-500">Hold Ctrl/⌘ to select multiple sites. Admins and site managers can access all sites.</p></div>; }
function UserModal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/40 p-4"><div className="my-auto w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h3 className="text-lg font-bold">{title}</h3><button onClick={close}>×</button></div>{children}</div></div>; }
