"use client";
import { useEffect, useState } from "react";
import { Cloud, KeyRound, LoaderCircle, Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Credential = { id: string; label: string; createdAt: string };
type Zone = { id: string; name: string; credentialId: string; credentialLabel: string };
type Record = { id: string; type: string; name: string; content: string; proxied: boolean; ttl: number };

export function DomainManager() {
  const [credentials, setCredentials] = useState<Credential[]>([]); const [zones, setZones] = useState<Zone[]>([]); const [selected, setSelected] = useState<Zone | null>(null); const [records, setRecords] = useState<Record[]>([]);
  const [busy, setBusy] = useState(true); const [addingCredential, setAddingCredential] = useState(false); const [addingRecord, setAddingRecord] = useState(false);
  const [editingRecord, setEditingRecord] = useState<Record | null>(null);
  async function load(refresh = false) { setBusy(true); try { const [c, z] = await Promise.all([fetch("/api/cloudflare/credentials").then((r) => r.json()), fetch(`/api/cloudflare/zones${refresh ? "?refresh=true" : ""}`).then((r) => r.json())]); if (!c.success) throw new Error(c.error.message); if (!z.success) throw new Error(z.error.message); setCredentials(c.data.credentials); setZones(z.data.zones); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not load domains"); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function select(zone: Zone) { setSelected(zone); setBusy(true); try { const result = await fetch(`/api/cloudflare/records?credentialId=${encodeURIComponent(zone.credentialId)}&zoneId=${encodeURIComponent(zone.id)}`).then((r) => r.json()); if (!result.success) throw new Error(result.error.message); setRecords(result.data.records); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not load DNS records"); } finally { setBusy(false); } }
  async function addCredential(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await fetch("/api/cloudflare/credentials", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }).then((r) => r.json()); if (!result.success) throw new Error(result.error.message); setAddingCredential(false); toast.success("Cloudflare account connected"); await load(true); } catch (e) { toast.error(e instanceof Error ? e.message : "Connection failed"); setBusy(false); } }
  async function removeCredential(item: Credential) { if (!confirm(`Disconnect ${item.label}? DNS records will not be changed.`)) return; setBusy(true); try { const result = await fetch("/api/cloudflare/credentials", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id }) }).then((r) => r.json()); if (!result.success) throw new Error(result.error.message); if (selected?.credentialId === item.id) { setSelected(null); setRecords([]); } await load(true); toast.success("Cloudflare account disconnected"); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not disconnect account"); setBusy(false); } }
  async function addRecord(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await fetch("/api/cloudflare/records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: editingRecord ? "update" : "create", id: editingRecord?.id, credentialId: selected.credentialId, zoneId: selected.id, record: { ...values, ttl: 1, proxied: values.proxied === "true" } }) }).then((r) => r.json()); if (!result.success) throw new Error(result.error.message); setAddingRecord(false); setEditingRecord(null); toast.success(editingRecord ? "DNS record updated" : "DNS record created"); await select(selected); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not save record"); setBusy(false); } }
  async function removeRecord(record: Record) { if (!selected || !confirm(`Delete ${record.name}?`)) return; await fetch("/api/cloudflare/records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "delete", id: record.id, credentialId: selected.credentialId, zoneId: selected.id }) }); await select(selected); }
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">Domains & DNS</h2><p className="mt-1 text-sm text-slate-500">Cloudflare zones and records connected only to your account.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load(true)}><RefreshCw className={`h-4 w-4 ${busy ? "animate-spin" : ""}`} /> Refresh</Button><Button onClick={() => setAddingCredential(true)}><KeyRound className="h-4 w-4" /> Connect Cloudflare</Button></div></div>
    {!!credentials.length && <div className="flex flex-wrap gap-2">{credentials.map((item) => <div key={item.id} className="flex items-center gap-2 rounded-full border bg-white py-1 pl-3 pr-1 text-sm shadow-sm"><Cloud className="h-4 w-4 text-panel-500" />{item.label}<button className="rounded-full p-1 text-slate-400 hover:bg-red-50 hover:text-red-500" onClick={() => void removeCredential(item)} aria-label={`Disconnect ${item.label}`}><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div>}
    {!credentials.length && !busy ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><Cloud className="mx-auto h-10 w-10 text-panel-500" /><h3 className="mt-4 font-bold">Connect your first Cloudflare account</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Use an API token with Zone:Read and DNS:Edit permissions. Tokens are encrypted and isolated by CloudPanel user.</p><Button className="mt-5" onClick={() => setAddingCredential(true)}>Connect account</Button></section> : <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><aside className="rounded-2xl border bg-white p-3 shadow-card"><p className="px-3 py-2 text-xs font-bold uppercase tracking-wide text-slate-400">Cloudflare zones</p>{zones.map((zone) => <button key={`${zone.credentialId}:${zone.id}`} onClick={() => void select(zone)} className={`w-full rounded-xl px-3 py-3 text-left ${selected?.id === zone.id ? "bg-panel-50 text-panel-700" : "hover:bg-slate-50"}`}><b className="block text-sm">{zone.name}</b><span className="text-xs text-slate-400">{zone.credentialLabel}</span></button>)}</aside><section className="min-h-[500px] rounded-2xl border bg-white shadow-card">{selected ? <><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold">{selected.name}</h3><p className="text-xs text-slate-500">{records.length} DNS records</p></div><Button size="sm" onClick={() => { setEditingRecord(null); setAddingRecord(true); }}><Plus className="h-4 w-4" /> Add record</Button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Type</th><th className="p-3">Name</th><th className="p-3">Content</th><th className="p-3">Proxy</th><th /></tr></thead><tbody className="divide-y">{records.map((record) => <tr key={record.id}><td className="p-3"><span className="rounded bg-slate-100 px-2 py-1 font-mono text-xs">{record.type}</span></td><td className="p-3 font-medium">{record.name}</td><td className="max-w-xs truncate p-3 font-mono text-xs">{record.content}</td><td className="p-3">{record.proxied ? "Proxied" : "DNS only"}</td><td className="p-3 text-right"><Button variant="ghost" size="icon" onClick={() => { setEditingRecord(record); setAddingRecord(true); }}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => void removeRecord(record)}><Trash2 className="h-4 w-4 text-red-500" /></Button></td></tr>)}</tbody></table></div></> : <div className="grid h-full min-h-[500px] place-items-center text-sm text-slate-400">Select a zone to manage its records</div>}</section></div>}
    {busy && <div className="fixed bottom-6 right-6 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl"><LoaderCircle className="h-4 w-4 animate-spin" /> Syncing Cloudflare…</div>}
    {addingCredential && <Modal title="Connect Cloudflare" close={() => setAddingCredential(false)}><form className="space-y-4" onSubmit={addCredential}><div><Label>Account label</Label><Input name="label" placeholder="Production account" required /></div><div><Label>API token</Label><Input name="token" type="password" autoComplete="off" required /><p className="mt-1 text-xs text-slate-500">Required permissions: Zone Read and DNS Edit.</p></div><Button disabled={busy}>Verify and connect</Button></form></Modal>}
    {addingRecord && selected && <Modal title={`${editingRecord ? "Edit" : "Add"} DNS record · ${selected.name}`} close={() => { setAddingRecord(false); setEditingRecord(null); }}><form className="space-y-4" onSubmit={addRecord}><div><Label>Type</Label><select name="type" defaultValue={editingRecord?.type ?? "A"} className="h-11 w-full rounded-lg border px-3"><option>A</option><option>AAAA</option><option>CNAME</option><option>TXT</option><option>MX</option></select></div><div><Label>Name</Label><Input name="name" defaultValue={editingRecord?.name ?? selected.name} required /></div><div><Label>Content</Label><Input name="content" defaultValue={editingRecord?.content} required /></div><label className="flex gap-2 text-sm"><input type="checkbox" name="proxied" value="true" defaultChecked={editingRecord?.proxied} /> Proxy through Cloudflare</label><Button disabled={busy}>{editingRecord ? "Save record" : "Create record"}</Button></form></Modal>}
  </div>;
}
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h3 className="text-lg font-bold">{title}</h3><button onClick={close}>×</button></div>{children}</div></div>; }
