"use client";
import { useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Check, GitBranch, GitCommit, GitFork, LoaderCircle, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type GitData = { isRepository: boolean; path: string; branch?: string; head?: string; remotes?: string[][]; branches?: string[]; changes?: { status: string; path: string }[]; commits?: { hash: string; author: string; date: string; subject: string }[]; diff?: string };
export function GitManager({ domain, initialData }: { domain: string; initialData: GitData }) {
  const [data, setData] = useState(initialData); const [busy, setBusy] = useState(false); const [remoteOpen, setRemoteOpen] = useState(false); const [commitOpen, setCommitOpen] = useState(false);
  async function action(input: Record<string, unknown>, message: string) { setBusy(true); try { const result = await fetch(`/api/sites/${encodeURIComponent(domain)}/sections/git`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }).then((r) => r.json()); if (!result.success) throw new Error(result.error?.message || "Git operation failed"); setData(result.data); toast.success(message); return true; } catch (e) { toast.error(e instanceof Error ? e.message : "Git operation failed"); return false; } finally { setBusy(false); } }
  if (!data.isRepository) return <section className="rounded-2xl border border-slate-200 bg-white p-8 shadow-card"><div className="mx-auto max-w-2xl text-center"><GitFork className="mx-auto h-12 w-12 text-panel-500" /><h3 className="mt-4 text-xl font-bold">Connect a Git repository</h3><p className="mt-2 text-sm text-slate-500">Clone into an empty site directory, or initialize Git around files already here.</p></div><form className="mx-auto mt-7 max-w-2xl space-y-4 rounded-xl bg-slate-50 p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: "clone", url: form.get("url"), branch: form.get("branch") }, "Repository cloned"); }}><div><Label>Repository URL</Label><Input name="url" placeholder="git@github.com:owner/repository.git" required /></div><div><Label>Branch (optional)</Label><Input name="branch" placeholder="main" /></div><Button disabled={busy}>{busy && <LoaderCircle className="h-4 w-4 animate-spin" />} Clone repository</Button><p className="text-xs text-slate-500">SSH URLs use this site user&apos;s deployment key. The directory must be empty.</p></form><div className="mx-auto mt-5 flex max-w-2xl items-center gap-3"><span className="h-px flex-1 bg-slate-200" /><span className="text-xs text-slate-400">or keep existing files</span><span className="h-px flex-1 bg-slate-200" /></div><div className="mt-5 text-center"><Button variant="outline" disabled={busy} onClick={() => void action({ action: "init" }, "Repository initialized")}>Initialize existing directory</Button></div></section>;
  const origin = data.remotes?.find((r) => r[0] === "origin" && r[2] === "(fetch)")?.[1];
  return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><GitBranch className="h-5 w-5 text-panel-600" /><h3 className="font-bold">{data.branch || "Detached HEAD"}</h3><code className="rounded bg-slate-100 px-2 py-1 text-xs">{data.head || "No commits"}</code></div><p className="mt-2 text-xs text-slate-500">{origin || "No origin remote configured"}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setRemoteOpen(true)}>Remote</Button><Button variant="outline" size="sm" disabled={busy || !origin} onClick={() => void action({ action: "fetch" }, "Remote fetched")}><RefreshCw className="h-4 w-4" /> Fetch</Button><Button variant="outline" size="sm" disabled={busy || !origin} onClick={() => void action({ action: "pull", branch: data.branch }, "Pulled latest changes")}><ArrowDownToLine className="h-4 w-4" /> Pull</Button><Button size="sm" disabled={busy || !origin} onClick={() => void action({ action: "push", branch: data.branch }, "Changes pushed")}><ArrowUpFromLine className="h-4 w-4" /> Push</Button></div></div></section>
    <div className="grid gap-5 lg:grid-cols-[1fr_420px]"><section className="rounded-2xl border bg-white shadow-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold">Working tree</h3><p className="text-xs text-slate-500">{data.changes?.length ?? 0} changed files</p></div><Button size="sm" disabled={!data.changes?.length} onClick={() => setCommitOpen(true)}><GitCommit className="h-4 w-4" /> Commit</Button></div>{data.changes?.length ? <div className="divide-y">{data.changes.map((change) => <div key={change.path} className="flex gap-3 px-5 py-3 text-sm"><code className="w-7 text-amber-600">{change.status}</code><span>{change.path}</span></div>)}</div> : <div className="p-10 text-center text-sm text-slate-400"><Check className="mx-auto mb-2 h-6 w-6 text-emerald-500" />Working tree is clean</div>}</section><section className="rounded-2xl border bg-white shadow-card"><div className="border-b px-5 py-4"><h3 className="font-bold">Branches</h3></div><div className="p-3">{data.branches?.map((branch) => <button key={branch} disabled={branch === data.branch || busy} onClick={() => void action({ action: "checkout", branch }, `Switched to ${branch}`)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm ${branch === data.branch ? "bg-panel-50 font-semibold text-panel-700" : "hover:bg-slate-50"}`}><GitBranch className="h-4 w-4" />{branch}</button>)}</div></section></div>
    {data.diff && <section className="overflow-hidden rounded-2xl border bg-white shadow-card"><div className="border-b px-5 py-4"><h3 className="font-bold">Uncommitted diff</h3></div><pre className="max-h-[55vh] overflow-auto bg-slate-950 p-5 text-xs leading-5 text-slate-200">{data.diff}</pre></section>}
    <section className="rounded-2xl border bg-white shadow-card"><div className="border-b px-5 py-4"><h3 className="font-bold">Recent commits</h3></div><div className="divide-y">{data.commits?.map((commit) => <div key={commit.hash} className="grid gap-1 px-5 py-3 sm:grid-cols-[90px_1fr_220px]"><code className="text-panel-600">{commit.hash}</code><span className="text-sm font-medium">{commit.subject}</span><span className="text-xs text-slate-400">{commit.author} · {commit.date}</span></div>)}</div></section>
    {remoteOpen && <Modal title="Origin remote" close={() => setRemoteOpen(false)}><form className="space-y-4" onSubmit={async (e) => { e.preventDefault(); const url = String(new FormData(e.currentTarget).get("url")); if (await action({ action: "set-remote", url }, "Remote updated")) setRemoteOpen(false); }}><div><Label>Git URL</Label><Input name="url" defaultValue={origin} placeholder="git@github.com:owner/repository.git" required /></div><p className="text-xs text-slate-500">SSH remotes use the deployment key shown under SSH/FTP.</p><Button disabled={busy}>Save remote</Button></form></Modal>}
    {commitOpen && <Modal title="Commit changes" close={() => setCommitOpen(false)}><form className="space-y-4" onSubmit={async (e) => { e.preventDefault(); const message = String(new FormData(e.currentTarget).get("message")); if (await action({ action: "commit", message }, "Changes committed")) setCommitOpen(false); }}><div><Label>Commit message</Label><Input name="message" autoFocus required /></div><Button disabled={busy}>Commit all changes</Button></form></Modal>}
  </div>;
}
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h3 className="text-lg font-bold">{title}</h3><button onClick={close}>×</button></div>{children}</div></div>; }
