"use client";
import { useState } from "react";
import { Activity, LoaderCircle, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { MonitoringSettings } from "@/server/monitoring/store";

export function MonitoringManager({ initialSettings }: { initialSettings: MonitoringSettings }) {
  const [form, setForm] = useState(initialSettings); const [busy, setBusy] = useState(false);
  const resource = (key: string, value: unknown) => setForm((current) => ({ ...current, resources: { ...current.resources, [key]: value } }));
  async function save() { setBusy(true); try { const response = await fetch("/api/monitoring/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!result.success) throw new Error(result.error?.message || "Monitoring settings could not be saved."); setForm(result.data); toast.success("Monitoring rules saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Monitoring settings could not be saved."); } finally { setBusy(false); } }
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card"><div className="flex items-center gap-3 border-b border-slate-100 bg-slate-50/60 px-5 py-4 sm:px-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-panel-50 text-panel-600"><Activity className="h-5 w-5" /></span><div><h3 className="font-bold">Monitoring rules</h3><p className="text-sm text-slate-500">Debounced resource thresholds plus certificate and update events.</p></div></div><div className="space-y-5 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.resources.enabled} onChange={(event) => resource("enabled", event.target.checked)} /> Resource alerts</label>{[["CPU %", "cpu"], ["Memory %", "memory"], ["Disk %", "disk"]].map(([label, key]) => <div key={key}><Label>{label}</Label><Input type="number" min={1} max={100} value={form.resources[key as "cpu" | "memory" | "disk"]} onChange={(event) => resource(key, Number(event.target.value))} /></div>)}<div><Label>Consecutive samples</Label><Input type="number" min={1} max={15} value={form.resources.consecutiveSamples} onChange={(event) => resource("consecutiveSamples", Number(event.target.value))} /></div><div><Label>Failed uptime checks</Label><Input type="number" min={1} max={10} value={form.uptimeFailureSamples} onChange={(event) => setForm((current) => ({ ...current, uptimeFailureSamples: Number(event.target.value) }))} /></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.sslEnabled} onChange={(event) => setForm((current) => ({ ...current, sslEnabled: event.target.checked }))} /> Certificate expiry</label><div><Label>Warn before days</Label><Input type="number" min={1} max={90} value={form.sslDays} onChange={(event) => setForm((current) => ({ ...current, sslDays: Number(event.target.value) }))} /></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.updatesEnabled} onChange={(event) => setForm((current) => ({ ...current, updatesEnabled: event.target.checked }))} /> Update available</label></div><Button disabled={busy} onClick={() => void save()}>{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save monitoring rules</Button></div></section>;
}
